homeassistant:
  customize: !include customize.yaml
  whitelist_external_dirs:
    - "/tmp"

frontend:
  themes: !include_dir_merge_named themes

config:
updater:
system_health:
stream:
history:
logbook:
map:
sun:
websocket_api:
mobile_app:
wake_on_lan:

recorder:
  purge_keep_days: 5

http:
  use_x_forwarded_for: true
  trusted_proxies: 172.17.0.4
  cors_allowed_origins:
    - https://cast.home-assistant.io

hacs:
  token: !secret hacs_token

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    delay_time: 60

yeelight:
  devices:
    192.168.0.164:
      name: Living Room
    192.168.0.188:
      name: Dining Table
    192.168.0.49:
      name: Bedside Lamp
    192.168.0.144:
      name: Kitchen Lightstrip
    192.168.0.189:
      name: Corner Lamp
    192.168.0.232:
      name: Nursery Cupboard Lamp
    192.168.0.218:
      name: Nursery Standing Lamp

media_extractor:
  default_query: bestaudio[ext=m4a]

climate:
  - platform: generic_thermostat
    name: "Bedroom Thermostat"
    heater: switch.bedroom_heater
    target_sensor: sensor.bedroom_sensor_temperature
    target_temp: 18.0
    min_temp: 15
    max_temp: 23

  - platform: generic_thermostat
    name: "Nursery Thermostat"
    heater: switch.washing_machine
    target_sensor: sensor.nursery_temp
    target_temp: 18.0
    min_temp: 15
    max_temp: 23

  - platform: generic_thermostat
    name: "Living Room Thermostat"
    heater: switch.living_room_heater
    target_sensor: sensor.living_room_temp
    target_temp: 18.0
    min_temp: 15
    max_temp: 23

weather:
  - platform: darksky
    api_key: !secret darksy_api_key

tts:
  - platform: google_translate
    service_name: google_say
    language: "en-us"
    base_url: http://192.168.0.87:8123

zwave:
  usb_path: /dev/ttyACM0

mqtt:
  broker: 192.168.0.87
  discovery: true
  discovery_prefix: homeassistant

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_secret

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.0.1/24
    home_interval: 15
    consider_home: 180
    new_device_defaults:
      track_new_devices: True
    exclude:
      - 192.168.0.6
      - 192.168.0.7
      - 192.168.0.8
      - 192.168.0.87

camera:
  - platform: ffmpeg
    input: -rtsp_transport tcp -i rtsp://192.168.0.9:6554/stream_0
    name: Nursery

  - platform: generic
    name: Vacuum Map
    still_image_url: http://192.168.0.7:3030/api/map/image
    content_type: image/png
    framerate: 1

joaoapps_join:
  - name: android
    device_id: !secret join_device_id
    api_key: !secret join_api_key

google_assistant:
  project_id: !secret gprojectid
  expose_by_default: false
  entity_config:
    light.living_room_lights:
      name: Living Room Lights
      room: living room
      expose: true
    light.tv_backlight:
      name: TV Backlight
      room: living room
      expose: true
    light.corner_lamp:
      name: Corner Lamp
      room: bedroom
      expose: true
    light.kitchen_lightstrip:
      name: Kitchen Lightstrip
      room: kitchen
      expose: true
    light.bedside_lamp:
      name: Bedroom Bedside Lamp
      room: bedroom
      expose: true
    switch.bedroom_fan:
      name: Bedroom Fan
      room: bedroom
      expose: true
    light.kitchen_counter:
      name: Kitchen Lights
      room: kitchen
      expose: true
    light.office:
      name: Office Light
      room: office
      expose: true
    light.nursery_standing_lamp:
      name: Nursery Standing Lamp
      room: nursery
      expose: true
    climate.bedroom_thermostat:
      name: Bedroom Thermostat
      room: bedroom
      expose: true
    climate.living_room_thermostat:
      name: Living Room Thermostat
      room: bedroom
      expose: true
    climate.nursery_thermostat:
      name: Nursery Thermostat
      room: nursery
      expose: true
    vacuum.rockrobo:
      name: Vacuum
      expose: true
      room: living room
    camera.nursery:
      name: Nursery
      expose: true
      room: bedroom
    input_boolean.baby_sleep:
      name: White Noise
      expose: true
      room: bedroom

light:
  - platform: group
    name: Living Room Lights
    entities:
      - light.living_room
      - light.dining_table

  - platform: group
    name: Bedroom Lights
    entities:
      - light.bedside_lamp
      - light.corner_lamp

  - platform: group
    name: Kitchen Lights
    entities:
      - light.kitchen_counter
      - light.kitchen_lightstrip

  - platform: group
    name: Nursery Lights
    entities:
      - light.nursery_cupboard_lamp
      - light.nursery_standing_lamp

media_player:
  - platform: smartir
    name: Living room TV Remote
    unique_id: living_room_tv_remote
    device_code: 1100
    controller_data: 192.168.0.115

automation: !include_dir_merge_list automations
script: !include scripts.yaml
switch: !include switches.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include sensors.yaml
notify: !include notify.yaml
input_boolean: !include input_booleans.yaml
zone: !include zones.yaml
group: !include groups.yaml